<a href="https://colab.research.google.com/github/EstebanJM/V.Data/blob/main/03_DataStructures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a DS?**

A DS is an object that let us store more than one value

Formally, a DS is a **Sequence** of values which can be located with an index. 

## **2. Linear Algebra**

## 2.1 What is Numpy ?

Numpy (Numerical Phyton) is a collection of functions and methods

In [1]:
# Instal library

import numpy as np

## 2.2 Numpy arrays - vectors and matrices

Example 1 - column vector



In [ ]:
a = np.array([[1],[2],[3]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]]
(3, 1)


Example 2 - row vector

In [ ]:
b = np.array ([[4,5,6]])
print(b)
print (b.shape)

[[4 5 6]]
(1, 3)


Example 3 - Matrix

In [ ]:
M = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# Nice trick

nr, nc = M.shape

# 2.3. Scilling

To acces one or several elements of the object

In [ ]:
# Extract the first element

## Column vector
print(a[0,0])

## row vector
print(b[0,0])

## Matrix
print(M[0,0])

1
4
1


In [ ]:
# Extract the last element

## Column vector
print(a[-1,0])

## row vector
print(b[0,-1])

## Matrix
print(M[-1,-1])

3
6
9


In [ ]:
# Extract a subset

## Column vector
print(a[0:2])

## row vector
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[[1]
 [2]]
[4 5]
[[1 2]
 [4 5]]


## 2.4 Methods

In [ ]:
# ZEROS

z1 = np.zeros(4)
print(z1)

z2 = np.zeros((3,2))
print(z2)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# ONES
o1 = np.ones(4)
print(o1)

o2 = np.ones((3,2))
print(o2)

o2*5


[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[5., 5.],
       [5., 5.],
       [5., 5.]])

**ANOTHER CREATION OPTIONS**

In [ ]:
# Full

f = np.full((3,2),5)
print(f)

[[5 5]
 [5 5]
 [5 5]]


In [ ]:
# Lineal sequence

np.arange(6)
np.arange(23,33)
np.arange(23,33,0.5)

array([23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5])

In [ ]:
# Linear space

np.linspace(15,90,6)

array([15., 30., 45., 60., 75., 90.])

## 2.5. Random numbers

### Uniform distribution (0,1)

In [ ]:
# a single value - between 0 - 1
np.random.seed(1234)
np.random.rand()

0.1915194503788923

In [ ]:
# Example - toss a coin

if np.random.rand() < 0.5:
  print("head")
else:
  print("tails")


head


In [ ]:
# Example 2
if np.random.rand() < 0.25:
  print("You win")
else:
  print("You lose")


You win


In [ ]:
#Example 3

ft= np.random.rand()

if ft < 0.5:
  print("The first toss was head")
else:
  print("The first toss was tails")

st = np.random.rand()
if st < 0.5:
  print("The second toss was head")
else:
  print("The second toss was tails")

if ft < 0.5 and st < 0.5:
  print("You win")
elif ft > 0.5 and st > 0.5:
  print("You win")
else:
 print("You lose")  

The first toss was tails
The second toss was tails
You win


In [ ]:
#Example 5
ft= np.random.rand() 
st = np.random.rand()

print("The first toss was head," if ft < 0.5 else "The first toss was tails,",
      "The second toss was head," if st < 0.5 else "The second toss was tails,", 
      "YOU WIN!" if ft < 0.5 and st < 0.5 else "YOU LOSE!")


The first toss was tails, The second toss was head, YOU LOSE!


In [ ]:
# One dimensional array

np.random.rand(5)

array([0.14409925, 0.3693503 , 0.83500957, 0.98295564, 0.2833897 ])

In [ ]:
# Matrix 
np.random.rand(6,2)

array([[0.06534146, 0.54396669],
       [0.16774171, 0.38996611],
       [0.64145178, 0.96264111],
       [0.3763073 , 0.93190123],
       [0.35536884, 0.11006601],
       [0.44826971, 0.00703775]])

### Uniform distribution (a,b)

In [ ]:
# Single value
np.random.uniform(low = -10, high = 0)

-6.223836017859576

In [ ]:
# One dimensional array
np.random.uniform(low =-10,high =0, size =7)

array([-4.63877242, -9.64448364, -9.49722287, -2.64611177, -7.4990488 ,
       -9.17556062, -0.70934769])

In [ ]:
# Matrix
np.random.uniform(low =-10,high =0, size = (5,2))

array([[-4.29651869, -9.41485662],
       [-1.25222136, -1.52315817],
       [-1.92925239, -6.39603157],
       [-3.71707099, -8.57868021],
       [-5.43863417, -7.54088324]])

In [7]:
#Exercise

for i in range (1,6):
 vt= np.random.rand()
if vt < 0.25:
  print("Day:", i, "Bad Week")
elif 0.25 <vt < 0.75:
  print("Day:", i,"Normal Week")
else:
  print("Day:", i,"Good week")


Day: 5 Good week


## Normal distribution

In [10]:
# Normal standard

np.random.randn()
np.random.randn(5)
np.random.randn(4,3)

array([[ 0.02836053,  1.50840182, -1.15917404],
       [ 0.65715341, -0.52128519,  0.76039064],
       [ 0.16270096,  0.78308417,  0.62837188],
       [-0.02700853,  0.25112304, -1.38892298]])

In [14]:
# Normal 

mu = 0.01
sigma = 0.1

np.random.normal(mu, sigma)
np.random.normal(mu, sigma, size = 5)
np.random.normal(mu, sigma, size = (3,5))

array([[ 0.1838332 ,  0.02753945, -0.16454864, -0.01784541,  0.3257516 ],
       [-0.14345884, -0.04029314,  0.04983814, -0.09811578, -0.14454734],
       [ 0.13420505, -0.105704  ,  0.02108856,  0.1756098 ,  0.11268916]])